
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7C800, LENGTH = 0x3800
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
. = 0x4C000;
C_L1L3_1_buff_0 = .;
. += 0x800;
. = 0x40400;
B_L3L1_1_cons_buff_0 = .;
. += 0x1000;
. = 0x44000;
A_L3L1_1_cons_buff_0 = .;
. += 0x1000;
. = 0x48000;
A_L3L1_1_cons_buff_1 = .;
. += 0x1000;
/* No tile with memory exists to the west. */
. = 0x50000;
. += 0x10000;
. = 0x6C000;
C_L1L3_3_buff_0 = .;
. += 0x800;
. = 0x60400;
B_L3L1_3_cons_buff_0 = .;
. += 0x1000;
. = 0x64000;
A_L3L1_3_cons_buff_0 = .;
. += 0x1000;
. = 0x68000;
A_L3L1_3_cons_buff_1 = .;
. += 0x1000;
. = 0x7C000;
C_L1L3_2_buff_0 = .;
. += 0x800;
. = 0x70400;
B_L3L1_2_cons_buff_0 = .;
. += 0x1000;
. = 0x74000;
A_L3L1_2_cons_buff_0 = .;
. += 0x1000;
. = 0x78000;
A_L3L1_2_cons_buff_1 = .;
. += 0x1000;
  .bss : { *(.bss*) } > data
}
INPUT(mv.o)
PROVIDE(main = core_0_4);
